// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/Array.proto

package ru.spbau.fedorov.architectures.protocol;

public final class ArrayMessage {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_tutorial_Array_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_tutorial_Array_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\036src/main/resources/Array.proto\022\010generate" +
                        "\"\025\n\005Array\022\014\n\004data\030\001 \003(\005B\034\n\014ru.spbau.fedorov.architectures.protocol" +
                        "B\014ArrayMessage"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_tutorial_Array_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_tutorial_Array_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_tutorial_Array_descriptor,
                new java.lang.String[]{"Data",});
    }

    private ArrayMessage() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface ArrayOrBuilder extends
            // @@protoc_insertion_point(interface_extends:tutorial.Array)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>repeated int32 data = 1;</code>
         */
        java.util.List<java.lang.Integer> getDataList();

        /**
         * <code>repeated int32 data = 1;</code>
         */
        int getDataCount();

        /**
         * <code>repeated int32 data = 1;</code>
         */
        int getData(int index);
    }

    /**
     * Protobuf type {@code tutorial.Array}
     */
    public static final class Array extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:tutorial.Array)
            ArrayOrBuilder {
        public static final int DATA_FIELD_NUMBER = 1;
        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<Array>
                PARSER = new com.google.protobuf.AbstractParser<Array>() {
            public Array parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Array(input, extensionRegistry);
            }
        };
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:tutorial.Array)
        private static final ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array();
        }

        private java.util.List<java.lang.Integer> data_;
        private byte memoizedIsInitialized = -1;

        // Use Array.newBuilder() to construct.
        private Array(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Array() {
            data_ = java.util.Collections.emptyList();
        }

        private Array(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                                data_ = new java.util.ArrayList<java.lang.Integer>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            data_.add(input.readInt32());
                            break;
                        }
                        case 10: {
                            int length = input.readRawVarint32();
                            int limit = input.pushLimit(length);
                            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                                data_ = new java.util.ArrayList<java.lang.Integer>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            while (input.getBytesUntilLimit() > 0) {
                                data_.add(input.readInt32());
                            }
                            input.popLimit(limit);
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                    data_ = java.util.Collections.unmodifiableList(data_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return ru.spbau.fedorov.architectures.protocol.ArrayMessage.internal_static_tutorial_Array_descriptor;
        }

        /**
         * <code>repeated int32 data = 1;</code>
         */
        public int getDataCount() {
            return data_.size();
        }

        public static ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        /**
         * <code>repeated int32 data = 1;</code>
         */
        public int getData(int index) {
            return data_.get(index);
        }

        public static ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<Array> parser() {
            return PARSER;
        }

        /**
         * <code>repeated int32 data = 1;</code>
         */
        public java.util.List<java.lang.Integer>
        getDataList() {
            return data_;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array)) {
                return super.equals(obj);
            }
            ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array other = (ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array) obj;

            boolean result = true;
            result = result && getDataList()
                    .equals(other.getDataList());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (getDataCount() > 0) {
                hash = (37 * hash) + DATA_FIELD_NUMBER;
                hash = (53 * hash) + getDataList().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Array> getParserForType() {
            return PARSER;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return ru.spbau.fedorov.architectures.protocol.ArrayMessage.internal_static_tutorial_Array_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array.class, ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array.Builder.class);
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) {
                return true;
            }
            if (isInitialized == 0) {
                return false;
            }

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            for (int i = 0; i < data_.size(); i++) {
                output.writeInt32(1, data_.get(i));
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            {
                int dataSize = 0;
                for (int i = 0; i < data_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream
                            .computeInt32SizeNoTag(data_.get(i));
                }
                size += dataSize;
                size += 1 * getDataList().size();
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code tutorial.Array}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:tutorial.Array)
                ru.spbau.fedorov.architectures.protocol.ArrayMessage.ArrayOrBuilder {
            private int bitField0_;
            private java.util.List<java.lang.Integer> data_ = java.util.Collections.emptyList();

            // Construct using ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return ru.spbau.fedorov.architectures.protocol.ArrayMessage.internal_static_tutorial_Array_descriptor;
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array getDefaultInstanceForType() {
                return ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array.getDefaultInstance();
            }

            public ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array build() {
                ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array buildPartial() {
                ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array result = new ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array(this);
                int from_bitField0_ = bitField0_;
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    data_ = java.util.Collections.unmodifiableList(data_);
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.data_ = data_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder clear() {
                super.clear();
                data_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return ru.spbau.fedorov.architectures.protocol.ArrayMessage.internal_static_tutorial_Array_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array.class, ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array.Builder.class);
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return ru.spbau.fedorov.architectures.protocol.ArrayMessage.internal_static_tutorial_Array_descriptor;
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array) {
                    return mergeFrom((ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            public Builder mergeFrom(ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array other) {
                if (other == ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array.getDefaultInstance()) {
                    return this;
                }
                if (!other.data_.isEmpty()) {
                    if (data_.isEmpty()) {
                        data_ = other.data_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                    } else {
                        ensureDataIsMutable();
                        data_.addAll(other.data_);
                    }
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            /**
             * <code>repeated int32 data = 1;</code>
             */
            public java.util.List<java.lang.Integer>
            getDataList() {
                return java.util.Collections.unmodifiableList(data_);
            }

            private void ensureDataIsMutable() {
                if (!((bitField0_ & 0x00000001) == 0x00000001)) {
                    data_ = new java.util.ArrayList<java.lang.Integer>(data_);
                    bitField0_ |= 0x00000001;
                }
            }

            /**
             * <code>repeated int32 data = 1;</code>
             */
            public int getDataCount() {
                return data_.size();
            }

            /**
             * <code>repeated int32 data = 1;</code>
             */
            public Builder setData(
                    int index, int value) {
                ensureDataIsMutable();
                data_.set(index, value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated int32 data = 1;</code>
             */
            public int getData(int index) {
                return data_.get(index);
            }

            /**
             * <code>repeated int32 data = 1;</code>
             */
            public Builder addData(int value) {
                ensureDataIsMutable();
                data_.add(value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated int32 data = 1;</code>
             */
            public Builder addAllData(
                    java.lang.Iterable<? extends java.lang.Integer> values) {
                ensureDataIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, data_);
                onChanged();
                return this;
            }

            /**
             * <code>repeated int32 data = 1;</code>
             */
            public Builder clearData() {
                data_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:tutorial.Array)
        }

        public ru.spbau.fedorov.architectures.protocol.ArrayMessage.Array getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}